// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASWQ5xi8bbOc5Ac4m_PIGn5kE8QRAuik8',
    appId: '1:788945908764:web:3ccb2f8cd08e250be41bd9',
    messagingSenderId: '788945908764',
    projectId: 'adv-exam-da923',
    authDomain: 'adv-exam-da923.firebaseapp.com',
    storageBucket: 'adv-exam-da923.appspot.com',
    measurementId: 'G-5NVXMK12E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCyNYSGetFEDd7Cggl6EgSFbAfot1ug4',
    appId: '1:788945908764:android:61ec1ad5ba8fa7e0e41bd9',
    messagingSenderId: '788945908764',
    projectId: 'adv-exam-da923',
    storageBucket: 'adv-exam-da923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKDD4IP8V3Cy-VECfNNdMi36OE38BDeA',
    appId: '1:788945908764:ios:b2ff2e1c062e23fae41bd9',
    messagingSenderId: '788945908764',
    projectId: 'adv-exam-da923',
    storageBucket: 'adv-exam-da923.appspot.com',
    iosBundleId: 'com.example.postApiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKDD4IP8V3Cy-VECfNNdMi36OE38BDeA',
    appId: '1:788945908764:ios:b2ff2e1c062e23fae41bd9',
    messagingSenderId: '788945908764',
    projectId: 'adv-exam-da923',
    storageBucket: 'adv-exam-da923.appspot.com',
    iosBundleId: 'com.example.postApiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASWQ5xi8bbOc5Ac4m_PIGn5kE8QRAuik8',
    appId: '1:788945908764:web:04fa70b4424527bfe41bd9',
    messagingSenderId: '788945908764',
    projectId: 'adv-exam-da923',
    authDomain: 'adv-exam-da923.firebaseapp.com',
    storageBucket: 'adv-exam-da923.appspot.com',
    measurementId: 'G-9WQE0VW5F0',
  );
}
